/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/gun-bot.glb 
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/gun-bot-with-walk-and-idle-animation-22c14d0bc65e41c4b2e936b67a958cf6
Title: Gun-Bot with walk and idle Animation
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei'

export function GunBot(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/gun-bot.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions['Default Take']) {
      actions['Default Take']
        .reset()
        .fadeIn(0.5)
        .play();
    }
  }, [actions]);
  return (
    <group scale={1.2} rotation={[0, Math.PI / 3, 0]} position={[2, -1.5, 7]} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fad22c5e9a934689aace770b3faeb3e9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="Cube_007" />
                  <group name="Cube_006" />
                  <group name="Cube_004" />
                  <group name="Cube_003" />
                  <group name="Cube_002" />
                  <group name="Cube_001" />
                  <group name="Cube_000" />
                  <group name="Cube_005" />
                  <group name="Hemi" position={[-2.394, 1.609, 2.582]} rotation={[0.87, -0.113, 0.584]}>
                    <group name="Object_90" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_91" />
                    </group>
                  </group>
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_13" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_15" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_18" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_22" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_24" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_27" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_33" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Spder_bot__Gun_Bot_N} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Spder_bot_Black__Gun_Bot_N} skeleton={nodes.Object_8.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Spder_bot__GB_N_jpg} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Spder_bot_Black__GB_N_jpg} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Spder_bot} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Spder_bot_Black} skeleton={nodes.Object_12.skeleton} />
                  <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Spder_bot__Gun_Bot_N_0} skeleton={nodes.Object_14.skeleton} />
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Spder_bot_Black__Gun_Bot_N_0} skeleton={nodes.Object_16.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Spder_bot__Gun_Bot_N_0} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Spder_bot_Black_0} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Spder_bot__GB_N_jpg_0} skeleton={nodes.Object_20.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Spder_bot_Black__GB_N_jpg_0} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Spder_bot_0} skeleton={nodes.Object_23.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Spder_bot__Gun_Bot_N_0} skeleton={nodes.Object_25.skeleton} />
                  <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Spder_bot_Black__Gun_Bot_N_1} skeleton={nodes.Object_26.skeleton} />
                  <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Spder_bot_1} skeleton={nodes.Object_28.skeleton} />
                  <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Spder_bot_Black_1} skeleton={nodes.Object_29.skeleton} />
                  <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Material_001} skeleton={nodes.Object_30.skeleton} />
                  <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Spder_bot__GB_C_jpg} skeleton={nodes.Object_31.skeleton} />
                  <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.Spder_bot_Black__GB_C_jpg} skeleton={nodes.Object_32.skeleton} />
                  <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Spder_bot_Black__Gun_Bot_N_2} skeleton={nodes.Object_34.skeleton} />
                  <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Spder_bot__Gun_Bot_N_1} skeleton={nodes.Object_35.skeleton} />
                  <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Spder_bot_2} skeleton={nodes.Object_36.skeleton} />
                  <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Spder_bot_Black_2} skeleton={nodes.Object_37.skeleton} />
                  <skinnedMesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Spder_bot__GB_N_jpg_1} skeleton={nodes.Object_38.skeleton} />
                  <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Spder_bot_Black__GB_N_jpg_1} skeleton={nodes.Object_39.skeleton} />
                  <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Grass} skeleton={nodes.Object_40.skeleton} />
                  <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Material} skeleton={nodes.Object_41.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gun-bot.glb')
